server:
  port: 9494

spring:
  datasource:
    name: dev
    url: jdbc:mysql://127.0.0.1:3306/springbootbbs
    username: root
    password: root
    hikari:
      maximum-pool-size: 3
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:/home/gs/111/javafiles/spring-boot-bbs/src/main/resources/static/
  jpa:
    show-sql: true
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB