server:
  port: 9494

spring:
  datasource:
    name: dev
    url: jdbc:mysql://192.168.1.6:3306/springbootbbs
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/