[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="springMacroRequestContext" type="org.springframework.web.servlet.support.RequestContext" --]
[#-- @ftlvariable name="message" type="String" --]
[#-- @ftlvariable name="_csrf" type="org.springframework.security.web.csrf.DefaultCsrfToken" --]
[#-- @ftlvariable name="query_str" type="String" --]
[#-- @ftlvariable name="user" type="com.springbootbbs.entiry.User" --]
[#-- @ftlvariable name="category" type="com.springbootbbs.entiry.Category" --]
[#-- @ftlvariable name="categories" type="Iterable<com.springbootbbs.entiry.Category>" --]
[#-- @ftlvariable name="page" type="org.springframework.data.domain.Page" --]
[#-- @ftlvariable name="topic" type="com.springbootbbs.entiry.Topic" --]
[#-- @ftlvariable name="post" type="com.springbootbbs.entiry.Post" --]
[#-- @ftlvariable name="show_date" type="com.springbootbbs.libs.helpers.ShowDate" --]
